spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/fisa
spring.datasource.username=fisa
spring.datasource.password=fisa
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
